# Generated by Django 3.1.7 on 2021-03-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_billing', '0003_auto_20210323_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billnumber',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
